begin;

create schema if not exists private;

create table if not exists public.assessment_attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  assessment_version integer not null,
  status text not null default 'active',
  started_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '2 hours'),
  completed_at timestamptz,
  result_summary jsonb not null default '{}'::jsonb,
  constraint assessment_attempts_status_check
    check (status in ('active', 'completed', 'expired'))
);

create index if not exists assessment_attempts_user_status_idx
  on public.assessment_attempts (user_id, status, started_at desc);

create unique index if not exists assessment_attempts_one_active_per_user_idx
  on public.assessment_attempts (user_id)
  where status = 'active';

create table if not exists public.assessment_attempt_actions (
  id bigint generated by default as identity primary key,
  attempt_id uuid not null references public.assessment_attempts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  request_id text not null,
  created_at timestamptz not null default now(),
  constraint assessment_attempt_actions_action_check
    check (action in ('transcribe', 'assessment_followup', 'assessment_evaluate')),
  constraint assessment_attempt_actions_request_unique
    unique (attempt_id, action, request_id)
);

create index if not exists assessment_attempt_actions_attempt_action_idx
  on public.assessment_attempt_actions (attempt_id, action);

create index if not exists assessment_attempt_actions_user_id_idx
  on public.assessment_attempt_actions (user_id);

alter table public.assessment_attempts enable row level security;
alter table public.assessment_attempts force row level security;
alter table public.assessment_attempt_actions enable row level security;
alter table public.assessment_attempt_actions force row level security;

revoke all on table public.assessment_attempts from anon, authenticated;
revoke all on table public.assessment_attempt_actions from anon, authenticated;
grant select on table public.assessment_attempts to authenticated;

drop policy if exists "Users can view own assessment attempts" on public.assessment_attempts;
create policy "Users can view own assessment attempts"
on public.assessment_attempts
for select
to authenticated
using ((select auth.uid()) = user_id);

create or replace function private.get_assessment_attempt_status()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_user_id uuid := auth.uid();
  actor_is_admin boolean := false;
  completed_count integer := 0;
  active_attempt public.assessment_attempts%rowtype;
begin
  if actor_user_id is null then
    raise exception 'LOGIN_REQUIRED';
  end if;

  perform pg_advisory_xact_lock(hashtextextended('assessment-user:' || actor_user_id::text, 0));

  select exists (
    select 1
    from public.user_access access
    where access.user_id = actor_user_id
      and access.role = 'admin'
      and access.access_status = 'active'
  ) into actor_is_admin;

  update public.assessment_attempts
  set status = 'expired'
  where user_id = actor_user_id
    and status = 'active'
    and expires_at <= now();

  select count(*)::integer
  into completed_count
  from public.assessment_attempts
  where user_id = actor_user_id
    and status = 'completed';

  select *
  into active_attempt
  from public.assessment_attempts
  where user_id = actor_user_id
    and status = 'active'
  order by started_at desc
  limit 1;

  return jsonb_build_object(
    'isAdmin', actor_is_admin,
    'maxAttempts', case when actor_is_admin then null else 3 end,
    'completedAttempts', completed_count,
    'remainingAttempts', case when actor_is_admin then null else greatest(0, 3 - completed_count) end,
    'activeAttemptId', active_attempt.id,
    'activeExpiresAt', active_attempt.expires_at
  );
end;
$$;

create or replace function private.start_assessment_attempt(input_assessment_version integer)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_user_id uuid := auth.uid();
  actor_is_admin boolean := false;
  completed_count integer := 0;
  active_attempt public.assessment_attempts%rowtype;
begin
  if actor_user_id is null then
    raise exception 'LOGIN_REQUIRED';
  end if;

  if input_assessment_version is null or input_assessment_version < 1 then
    raise exception 'ASSESSMENT_VERSION_REQUIRED';
  end if;

  if coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) then
    raise exception 'VERIFIED_ACCOUNT_REQUIRED';
  end if;

  if not exists (
    select 1
    from auth.users account
    where account.id = actor_user_id
      and account.email_confirmed_at is not null
  ) then
    raise exception 'VERIFIED_ACCOUNT_REQUIRED';
  end if;

  perform pg_advisory_xact_lock(hashtextextended('assessment-user:' || actor_user_id::text, 0));

  select exists (
    select 1
    from public.user_access access
    where access.user_id = actor_user_id
      and access.role = 'admin'
      and access.access_status = 'active'
  ) into actor_is_admin;

  update public.assessment_attempts
  set status = 'expired'
  where user_id = actor_user_id
    and status = 'active'
    and expires_at <= now();

  select *
  into active_attempt
  from public.assessment_attempts
  where user_id = actor_user_id
    and status = 'active'
  order by started_at desc
  limit 1;

  select count(*)::integer
  into completed_count
  from public.assessment_attempts
  where user_id = actor_user_id
    and status = 'completed';

  if active_attempt.id is null then
    if not actor_is_admin and completed_count >= 3 then
      raise exception 'ASSESSMENT_LIMIT_REACHED';
    end if;

    insert into public.assessment_attempts (user_id, assessment_version)
    values (actor_user_id, input_assessment_version)
    returning * into active_attempt;
  end if;

  return jsonb_build_object(
    'attemptId', active_attempt.id,
    'expiresAt', active_attempt.expires_at,
    'isAdmin', actor_is_admin,
    'maxAttempts', case when actor_is_admin then null else 3 end,
    'completedAttempts', completed_count,
    'remainingAttempts', case when actor_is_admin then null else greatest(0, 3 - completed_count) end
  );
end;
$$;

create or replace function private.authorize_assessment_action(
  input_attempt_id uuid,
  input_action text,
  input_request_id text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_user_id uuid := auth.uid();
  active_attempt public.assessment_attempts%rowtype;
  action_limit integer;
  action_count integer;
begin
  if actor_user_id is null then
    raise exception 'LOGIN_REQUIRED';
  end if;

  if input_attempt_id is null or nullif(trim(input_request_id), '') is null then
    raise exception 'ASSESSMENT_ATTEMPT_REQUIRED';
  end if;

  action_limit := case input_action
    when 'transcribe' then 10
    when 'assessment_followup' then 4
    when 'assessment_evaluate' then 3
    else null
  end;

  if action_limit is null then
    raise exception 'INVALID_ASSESSMENT_ACTION';
  end if;

  perform pg_advisory_xact_lock(hashtextextended('assessment-attempt:' || input_attempt_id::text, 0));

  select *
  into active_attempt
  from public.assessment_attempts
  where id = input_attempt_id
    and user_id = actor_user_id
  for update;

  if active_attempt.id is null then
    raise exception 'ASSESSMENT_ATTEMPT_NOT_FOUND';
  end if;

  if active_attempt.status <> 'active' then
    raise exception 'ASSESSMENT_ATTEMPT_NOT_ACTIVE';
  end if;

  if active_attempt.expires_at <= now() then
    update public.assessment_attempts
    set status = 'expired'
    where id = active_attempt.id;
    raise exception 'ASSESSMENT_ATTEMPT_EXPIRED';
  end if;

  if exists (
    select 1
    from public.assessment_attempt_actions
    where attempt_id = input_attempt_id
      and action = input_action
      and request_id = trim(input_request_id)
  ) then
    return true;
  end if;

  select count(*)::integer
  into action_count
  from public.assessment_attempt_actions
  where attempt_id = input_attempt_id
    and action = input_action;

  if action_count >= action_limit then
    raise exception 'ASSESSMENT_ACTION_LIMIT_REACHED';
  end if;

  insert into public.assessment_attempt_actions (attempt_id, user_id, action, request_id)
  values (input_attempt_id, actor_user_id, input_action, trim(input_request_id));

  return true;
end;
$$;

create or replace function private.complete_assessment_attempt(
  input_attempt_id uuid,
  input_result_summary jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_user_id uuid := auth.uid();
  actor_is_admin boolean := false;
  target_attempt public.assessment_attempts%rowtype;
  completed_count integer := 0;
begin
  if actor_user_id is null then
    raise exception 'LOGIN_REQUIRED';
  end if;

  perform pg_advisory_xact_lock(hashtextextended('assessment-user:' || actor_user_id::text, 0));

  select *
  into target_attempt
  from public.assessment_attempts
  where id = input_attempt_id
    and user_id = actor_user_id
  for update;

  if target_attempt.id is null then
    raise exception 'ASSESSMENT_ATTEMPT_NOT_FOUND';
  end if;

  if target_attempt.status = 'active' then
    if target_attempt.expires_at <= now() then
      update public.assessment_attempts
      set status = 'expired'
      where id = target_attempt.id;
      raise exception 'ASSESSMENT_ATTEMPT_EXPIRED';
    end if;

    if not exists (
      select 1
      from public.assessment_attempt_actions
      where attempt_id = input_attempt_id
        and action = 'assessment_evaluate'
    ) then
      raise exception 'ASSESSMENT_EVALUATION_REQUIRED';
    end if;

    update public.assessment_attempts
    set status = 'completed',
        completed_at = now(),
        result_summary = coalesce(input_result_summary, '{}'::jsonb)
    where id = target_attempt.id;
  elsif target_attempt.status <> 'completed' then
    raise exception 'ASSESSMENT_ATTEMPT_NOT_ACTIVE';
  end if;

  select exists (
    select 1
    from public.user_access access
    where access.user_id = actor_user_id
      and access.role = 'admin'
      and access.access_status = 'active'
  ) into actor_is_admin;

  select count(*)::integer
  into completed_count
  from public.assessment_attempts
  where user_id = actor_user_id
    and status = 'completed';

  return jsonb_build_object(
    'attemptId', target_attempt.id,
    'completedAttempts', completed_count,
    'remainingAttempts', case when actor_is_admin then null else greatest(0, 3 - completed_count) end,
    'maxAttempts', case when actor_is_admin then null else 3 end,
    'isAdmin', actor_is_admin
  );
end;
$$;

create or replace function private.get_assessment_evaluation_result(
  input_attempt_id uuid,
  input_request_id text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_user_id uuid := auth.uid();
  normalized_request_id text := nullif(left(trim(coalesce(input_request_id, '')), 200), '');
  target_attempt public.assessment_attempts%rowtype;
begin
  if actor_user_id is null then
    raise exception 'LOGIN_REQUIRED';
  end if;

  if input_attempt_id is null or normalized_request_id is null then
    raise exception 'ASSESSMENT_ATTEMPT_REQUIRED';
  end if;

  select *
  into target_attempt
  from public.assessment_attempts
  where id = input_attempt_id
    and user_id = actor_user_id;

  if target_attempt.id is null then
    raise exception 'ASSESSMENT_ATTEMPT_NOT_FOUND';
  end if;

  if target_attempt.status <> 'completed'
    or target_attempt.result_summary ->> 'requestId' is distinct from normalized_request_id
    or jsonb_typeof(target_attempt.result_summary -> 'evaluation') is distinct from 'object'
    or not exists (
      select 1
      from public.assessment_attempt_actions
      where attempt_id = input_attempt_id
        and user_id = actor_user_id
        and action = 'assessment_evaluate'
        and request_id = normalized_request_id
    ) then
    return null;
  end if;

  return target_attempt.result_summary -> 'evaluation';
end;
$$;

create or replace function public.get_assessment_attempt_status()
returns jsonb
language sql
security invoker
set search_path = ''
as $$
  select private.get_assessment_attempt_status();
$$;

create or replace function public.start_assessment_attempt(input_assessment_version integer)
returns jsonb
language sql
security invoker
set search_path = ''
as $$
  select private.start_assessment_attempt(input_assessment_version);
$$;

create or replace function public.authorize_assessment_action(
  input_attempt_id uuid,
  input_action text,
  input_request_id text
)
returns boolean
language sql
security invoker
set search_path = ''
as $$
  select private.authorize_assessment_action(input_attempt_id, input_action, input_request_id);
$$;

create or replace function public.complete_assessment_attempt(
  input_attempt_id uuid,
  input_result_summary jsonb default '{}'::jsonb
)
returns jsonb
language sql
security invoker
set search_path = ''
as $$
  select private.complete_assessment_attempt(input_attempt_id, input_result_summary);
$$;

create or replace function public.get_assessment_evaluation_result(
  input_attempt_id uuid,
  input_request_id text
)
returns jsonb
language sql
security invoker
set search_path = ''
as $$
  select private.get_assessment_evaluation_result(input_attempt_id, input_request_id);
$$;

revoke all on function private.get_assessment_attempt_status() from public, anon;
revoke all on function private.start_assessment_attempt(integer) from public, anon;
revoke all on function private.authorize_assessment_action(uuid, text, text) from public, anon;
revoke all on function private.complete_assessment_attempt(uuid, jsonb) from public, anon;
revoke all on function private.get_assessment_evaluation_result(uuid, text) from public, anon;

grant usage on schema private to authenticated;
grant execute on function private.get_assessment_attempt_status() to authenticated;
grant execute on function private.start_assessment_attempt(integer) to authenticated;
grant execute on function private.authorize_assessment_action(uuid, text, text) to authenticated;
grant execute on function private.complete_assessment_attempt(uuid, jsonb) to authenticated;
grant execute on function private.get_assessment_evaluation_result(uuid, text) to authenticated;

revoke all on function public.get_assessment_attempt_status() from public, anon;
revoke all on function public.start_assessment_attempt(integer) from public, anon;
revoke all on function public.authorize_assessment_action(uuid, text, text) from public, anon;
revoke all on function public.complete_assessment_attempt(uuid, jsonb) from public, anon;
revoke all on function public.get_assessment_evaluation_result(uuid, text) from public, anon;

grant execute on function public.get_assessment_attempt_status() to authenticated;
grant execute on function public.start_assessment_attempt(integer) to authenticated;
grant execute on function public.authorize_assessment_action(uuid, text, text) to authenticated;
grant execute on function public.complete_assessment_attempt(uuid, jsonb) to authenticated;
grant execute on function public.get_assessment_evaluation_result(uuid, text) to authenticated;

commit;

-- Verification: both tables must have RLS enabled and all five routines must be listed.
select relname, relrowsecurity, relforcerowsecurity
from pg_class
where relnamespace = 'public'::regnamespace
  and relname in ('assessment_attempts', 'assessment_attempt_actions')
order by relname;

select routine_name
from information_schema.routines
where routine_schema = 'public'
  and routine_name in (
    'get_assessment_attempt_status',
    'start_assessment_attempt',
    'authorize_assessment_action',
    'complete_assessment_attempt',
    'get_assessment_evaluation_result'
  )
order by routine_name;
