-- Deprecated: do not run this file.
--
-- The original version used an email allowlist and an older activation policy.
-- Running it could weaken the current role-based authorization model.
-- Use supabase_roles_and_access.sql for activation, membership, admin and mentor
-- setup. That script is idempotent and includes the required base tables.
