const simulationKnowledge = {
  bar_sim_basic_order: {
    role: 'Guest',
    openingLine: "Hi. Could I have one mojito, but not too sweet? And my wife would like something non-alcoholic.",
    followUpFocus: 'Ask for a non-alcoholic preference and verify whether the server restates the full order.',
    serviceGoal: 'Clarify, repeat back the order, and set a realistic next step.',
    salesGoal: 'Do not force an upsell; make the basic order accurate first.',
    knowledge: ['Ask one concise preference question before choosing the non-alcoholic drink.', 'Repeat the drink, quantity, and relevant modification.', 'Do not invent wait times, prices, or package coverage.'],
  },
  bar_sim_premium_recommendation: {
    role: 'Guest',
    openingLine: "I'd like something light, citrusy, and not too sweet. What do you recommend?",
    followUpFocus: 'Test whether the server can clarify base spirit, adjust sweetness, and offer a suitable premium alternative.',
    serviceGoal: 'Give a reliable drink recommendation based on the stated preference.',
    salesGoal: 'Offer a premium alternative only when it genuinely improves the guest choice.',
    knowledge: ['Vodka soda with fresh lime is light and low sweetness, but confirm the guest accepts vodka.', 'Tom Collins can fit when gin is acceptable; syrup level matters.', 'Package coverage and prices must be checked, never promised.'],
  },
  bar_sim_wrong_drink_recovery: {
    role: 'Complaining Guest',
    openingLine: "This isn't what I ordered. I've already waited twenty minutes, and now it's far too sweet.",
    followUpFocus: 'Test order verification, authorization awareness, and a clear service-recovery follow-up.',
    serviceGoal: 'Acknowledge, verify, remake or replace within policy, and close the loop.',
    salesGoal: 'No upsell. Restore trust first.',
    knowledge: ['Never blame the bartender, system, or guest in front of the guest.', 'Free drinks, refunds, and compensation may require supervisor authorization.', 'Follow up after the replacement arrives.'],
  },
  bar_sim_responsible_service: {
    role: 'Drunk Guest',
    openingLine: "I've got the package. Just give me another whisky. Don't make this difficult.",
    followUpFocus: 'Challenge package entitlement while testing calm refusal and escalation.',
    serviceGoal: 'Stop alcohol service calmly, offer a safe alternative, and escalate appropriately.',
    salesGoal: 'Not applicable. Safety overrides sales.',
    knowledge: ['A beverage package never overrides responsible-service policy.', 'Use neutral language rather than calling a guest drunk to their face.', 'Notify a supervisor early and request security or medical support if needed.'],
  },
  retail_sim_guest_approach: {
    jobKey: 'retail', position: 'Retail Sales Associate', role: 'Guest',
    openingLine: "Thanks, I'm just looking. I don't really need anything today.",
    followUpFocus: 'Test whether the associate can discover a purpose, recipient, category, or preference without becoming pushy.',
    serviceGoal: 'Welcome the guest, respect their space, and create a natural reason to continue.',
    salesGoal: 'Discover one useful preference without starting a product pitch.',
    knowledge: ['Offer specific help and remain available.', 'Use one relevant open question.', 'Respect a clear decision not to engage.'],
  },
  retail_sim_fragrance_discovery: {
    jobKey: 'retail', position: 'Retail Sales Associate', role: 'Gift Shopper',
    openingLine: "I need a fragrance for my partner, but I have no idea what to choose. They usually like something fresh.",
    followUpFocus: 'Ask about budget, scent family, current fragrance, or occasion before testing a comparison and close.',
    serviceGoal: 'Discover the need and present one suitable option with honest feature-to-benefit language.',
    salesGoal: 'Offer a relevant comparison or gift addition only after establishing fit.',
    knowledge: ['Ask about scent family, occasion, current favourites, and budget.', 'Describe notes rather than promising a reaction.', 'Never invent longevity, stock, or savings.'],
  },
  retail_sim_price_objection: {
    jobKey: 'retail', position: 'Retail Sales Associate', role: 'Price-conscious Guest',
    openingLine: 'I found what looks like the same watch online for less. Why should I buy it here?',
    followUpFocus: 'Challenge the associate on price matching, warranty, authenticity, or customs allowance.',
    serviceGoal: 'Acknowledge the comparison, verify facts, and protect trust.',
    salesGoal: 'Clarify value and buying conditions, then close only when the concern is resolved.',
    knowledge: ['Do not guarantee the lowest price or a customs outcome.', 'Compare exact model, warranty, currency, tax, and seller status.', 'Use approved price information only.'],
  },
  retail_sim_return_policy: {
    jobKey: 'retail', position: 'Retail Sales Associate', role: 'Complaining Guest',
    openingLine: 'This skincare set irritated my skin. I opened it yesterday and I want a full refund now.',
    followUpFocus: 'Test empathy, policy boundaries, escalation, and whether the associate avoids medical claims.',
    serviceGoal: 'Listen, inspect facts, explain only verified policy, and involve the correct authority.',
    salesGoal: 'Restore trust. Do not turn the complaint into an upsell.',
    knowledge: ['Check receipt, condition, purchase details, and current policy.', 'Do not promise a refund before authorisation.', 'Avoid medical advice and document the concern.'],
  },
  retail_sim_sea_day: {
    jobKey: 'retail', position: 'Retail Sales Associate', role: 'Event Guest',
    openingLine: 'The sign says buy two and save twenty percent. Does that include this brand, and can I mix the products?',
    followUpFocus: 'Add a waiting guest, an uncertain exclusion, or a stock issue and test prioritisation plus an accurate close.',
    serviceGoal: 'Prioritise guests, explain the promotion accurately, and keep the floor controlled.',
    salesGoal: 'Use needs-based cross-selling while protecting service and transaction accuracy.',
    knowledge: ['Acknowledge waiting guests.', 'Confirm eligibility and exclusions in approved material.', 'Protect merchandise, payment accuracy, and team communication.'],
  },
}

export const getBarServerSimulationKnowledge = (scenarioId) => simulationKnowledge[scenarioId] || null
